use_frameworks!

platform :ios, '9.0'

target 'FGPopupScheduler-Swift_Example' do
  pod 'FGPopupScheduler-Swift', :path => '../'

  target 'FGPopupScheduler-Swift_Tests' do
    inherit! :search_paths

    
  end
end
